### ISSUE TITLE
- [ ] Implementar prototipos de alta fidelidad enfocándose en la navegabilidad y usabilidad.

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo7_sa_ppi2020#14]

**Comment by brayan2003** [comment]
@JohnFlorez25  Terminado

**Comment by JohnFlorez25** [comment]
@brayan2003 @YereimiSanchez @jennymontoya1001 es importante que en el prototipo de alta fidelidad tengan en cuenta por lo menos una de las interacciones del usuario al pasar un TEMA o NIVEL y garantizando la obtención de los puntos o nota. Hay que tratar que los prototipos están un poco más acorde con las recomendaciones brindadas respecto a patrones de diseño. 

- Se tuvieron en cuenta las recomendaciones de la dinámica de la aplicación garantizando el alcance acordado en el primer cuadrante
