### ISSUE TITLE
- [ ] Definir los servicios del Backend que se deben implementar de acuerdo con las reglas de negocio. (Objeto JSON)

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo7_sa_ppi2020#17]

**Comment by JohnFlorez25** [comment]
@brayan2003 @YereimiSanchez El siguiente formato se especifica la estructura de como deben evidenciar cada uno de los servicios backend que van a ser consumidos desde el frontend (validar con la profe @jennymontoya1001 )
[Formato Definición de los servicios backend.docx](https://github.com/JohnFlorez25/equipo7_sa_ppi2020/files/5271460/Formato.Definicion.de.los.servicios.backend.docx)

**Comment by JohnFlorez25** [comment]
@jennymontoya1001 @brayan2003 @YereimiSanchez falta realizar el documento con la evidencia de la definición de los servicios backend

**Comment by brayan2003** [comment]
@JohnFlorez25 y @jennymontoya1001 terminado
