### ISSUE TITLE
Declarar la situación del problema

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo7_sa_ppi2020#3]

**Comment by JohnFlorez25** [comment]
@YereimiSanchez ampliar el problema e identificar otras causas

**Comment by JohnFlorez25** [comment]
La declaración de la situación del problema debe cumplir con la estructura de:

- Identificar cual es el problema

- Cuales son las causas de este problema

- En que tiene efecto

**Comment by brayan2003** [comment]
John, ya corregimos la declaración del problema
