### ISSUE TITLE
Realizar Historias de Usuario y criterios de aceptación

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo7_sa_ppi2020#8]

**Comment by brayan2003** [comment]
@JohnFlorez25 listo

**Comment by JohnFlorez25** [comment]
@brayan2003 @YereimiSanchez Deben ser como mínimo 10 historias de usuario con sus respectivos criterios de aceptación

**Comment by brayan2003** [comment]
@JohnFlorez25 terminado
